Updating credentials file

diff --git a/bin/generate_tfrc_credentials b/bin/generate_tfrc_credentials
--- a/bin/generate_tfrc_credentials
+++ b/bin/generate_tfrc_credentials
@@ -2,14 +2,27 @@
 
 # Check if TERRAFORM_CLOUD_TOKEN is set
 if [ -z "$TERRAFORM_CLOUD_TOKEN" ]; then
-    echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
-    exit 1
+  echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
+  exit 1
 fi
 
-# JSON content
-json_content="{\"credentials\": {\"app.terraform.io\": {\"token\": \"$TERRAFORM_CLOUD_TOKEN\"}}}"
+# Specify the target directory and file path
+target_directory="/home/gitpod/.terraform.d"
+target_file="$target_directory/credentials.tfrc.json"
 
-# Write JSON content to file
-echo "$json_content" > credentials.tfrc.json
+# Ensure the target directory exists, create it if not
+mkdir -p "$target_directory"
 
-echo "Credentials file generated successfully."
+# Define the JSON structure
+json_data='{
+  "credentials": {
+    "app.terraform.io": {
+      "token": "'"$TERRAFORM_CLOUD_TOKEN"'"
+    }
+  }
+}'
+
+# Create credentials.tfrc.json
+echo "$json_data" > "$target_file"
+
+echo "credentials.tfrc.json file has been generated in $target_file."
